# Generated by Django 4.1 on 2023-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(max_length=350, upload_to=''),
        ),
    ]
